2022-01-23 12:04:55,818 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 12:04:55,818 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 12:04:55,820 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 12:04:55,821 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 12:04:55,916 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 12:05:10,163 INFO     core.py Установлено соедение с ПК ('127.0.0.1', 63073)
2022-01-23 12:05:10,664 DEBUG    core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1642928710.17522, 'user': {'account_name': 'w', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1q0KYP3zH5a6o+nP0cl5\nFsmBVoSoL1HxJBBDbaHUTa2rWhKqG0STgqgQoxpQ+i+WIonwWvpMv/4v6TeZHjih\nlasHaMEeDy2ZOHQ3d5iCQMUcGgreXiDwpgui7s/6A9SoXxgem1+hSujJwlomuNAb\nUnr/QqeOetAAhdtuXrlBADkQgq0iY7DhLmpa2MBArirX2fAxDpUgf9Djb+wO3/Wr\nSGopIOpZpS09NIHekHKOCJqu8Lbw0VgXOVrmTmQbFJEPaos6209XpU1L+ZyN84K/\nvuCXKCRH9vBDfkMxCAbhWHVsk7kMTQkejqdu8r1H/ZgF05oHO4iY7jJHUcBlcgx7\nTQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-01-23 12:05:10,665 DEBUG    core.py Start auth process for {'account_name': 'w', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1q0KYP3zH5a6o+nP0cl5\nFsmBVoSoL1HxJBBDbaHUTa2rWhKqG0STgqgQoxpQ+i+WIonwWvpMv/4v6TeZHjih\nlasHaMEeDy2ZOHQ3d5iCQMUcGgreXiDwpgui7s/6A9SoXxgem1+hSujJwlomuNAb\nUnr/QqeOetAAhdtuXrlBADkQgq0iY7DhLmpa2MBArirX2fAxDpUgf9Djb+wO3/Wr\nSGopIOpZpS09NIHekHKOCJqu8Lbw0VgXOVrmTmQbFJEPaos6209XpU1L+ZyN84K/\nvuCXKCRH9vBDfkMxCAbhWHVsk7kMTQkejqdu8r1H/ZgF05oHO4iY7jJHUcBlcgx7\nTQIDAQAB\n-----END PUBLIC KEY-----'}
2022-01-23 12:05:10,671 DEBUG    core.py Correct username, starting passwd check.
2022-01-23 12:05:10,674 DEBUG    core.py Auth message = {'response': 511, 'bin': '3af5db403dba91f4cec7591ed7269096e84452c9bb803f25e4261b4cda8340017ee21b493bc47f4191f1c58d426ae46fae4e52ca8a3fd0b3f98c37612d6d9d0e'}
2022-01-23 12:05:11,185 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1642928710.675541, 'account_name': 'w'}
2022-01-23 12:05:11,701 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1642928711.209428, 'user': 'w'}
2022-01-23 12:05:26,306 INFO     core.py Установлено соедение с ПК ('127.0.0.1', 63075)
2022-01-23 12:05:26,808 DEBUG    core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1642928726.314164, 'user': {'account_name': 'kuznetsov', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApfjRhJI/Zhc24i0fljX0\nIgnAJS+q4HOhlCyY1p6+16SwlAA76zpQDLSrTTNMj2hlDBF92ePgAyYL2yLZL5q/\n+drVAX+MSLAkC+VORF9usHjasrv3aG0v3UCUSFVzdGGo59WD8a7XSH4f7oqwCGHP\n/vUOL8pEAONPChgMJQTf6rd60b56HlPColofK46RZeh8Xxi9EmrElXijPIEsNxVa\nUxEeL7lLm71GcZv+lgyTHA2xSZlR+VzXBeuzKeKl5g+qxFNx70bWNqi9LgD6ErjK\nJtEus3lUIZHP3STrd7w/ajkTX4ypfkpLdt5GY6tKTHPZcbz2wTSJ7NQqMFSTQz0t\nTQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-01-23 12:05:26,808 DEBUG    core.py Start auth process for {'account_name': 'kuznetsov', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApfjRhJI/Zhc24i0fljX0\nIgnAJS+q4HOhlCyY1p6+16SwlAA76zpQDLSrTTNMj2hlDBF92ePgAyYL2yLZL5q/\n+drVAX+MSLAkC+VORF9usHjasrv3aG0v3UCUSFVzdGGo59WD8a7XSH4f7oqwCGHP\n/vUOL8pEAONPChgMJQTf6rd60b56HlPColofK46RZeh8Xxi9EmrElXijPIEsNxVa\nUxEeL7lLm71GcZv+lgyTHA2xSZlR+VzXBeuzKeKl5g+qxFNx70bWNqi9LgD6ErjK\nJtEus3lUIZHP3STrd7w/ajkTX4ypfkpLdt5GY6tKTHPZcbz2wTSJ7NQqMFSTQz0t\nTQIDAQAB\n-----END PUBLIC KEY-----'}
2022-01-23 12:05:26,810 DEBUG    core.py Correct username, starting passwd check.
2022-01-23 12:05:26,811 DEBUG    core.py Auth message = {'response': 511, 'bin': 'cc2efed1d5f461141bdfa3b60b625fe5b4f1bea9ad5a580e4a6c931e08a163efe546d39ce3826da97c695441e534ec40cf6bab5af2a6f28f99bb2bf04dd3df0e'}
2022-01-23 12:05:27,323 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1642928726.812182, 'account_name': 'kuznetsov'}
2022-01-23 12:05:27,825 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1642928727.34029, 'user': 'kuznetsov'}
2022-01-23 12:05:30,332 DEBUG    core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1642928730.192343, 'account_name': 'w'}
2022-01-23 12:05:35,843 DEBUG    core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'kuznetsov', 'to': 'w', 'time': 1642928735.8367438, 'mess_text': 'usrbYO936MDJu4ZBfWy9yT8jUvmCEs0lcfUY+fdO8AHXVTUzATXgGccx9LixX4HSy7DjSMKzzC8jLuyeQS3KjgLtlBRn+N8lzUqG5rfVVa6cPEr+ExOHxrDTfgLO9EG3zGo34ERVhbD6C9eUqxILYZAs2sXcaM9CO5hL159iqNrsB6BJzaJbSFL385BaaBcal9+TQm92HrTISGhV2v7WAEq4mJjDozqWdm3QRjx7+W0bh/zJuoCJhUKPFFdl6d0lgAS89Ayyk+9WOOWy66mLeQyGczxh7vhIMb5OUmv4fq9LinqynLhp9gqWRjswSkI7Q74kxQi1X4G6GdiH6NML7g=='}
2022-01-23 12:05:35,851 INFO     core.py Отправлено сообщение пользователю w от пользователя kuznetsov.
2022-01-23 12:05:43,361 DEBUG    core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1642928743.276669, 'account_name': 'kuznetsov'}
2022-01-23 12:05:47,367 DEBUG    core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1642928746.8477361, 'account_name': 'w'}
2022-01-23 12:05:47,368 INFO     core.py Клиент ('127.0.0.1', 63073) отключился от сервера.
2022-01-23 12:05:48,379 DEBUG    core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1642928747.945733, 'account_name': 'kuznetsov'}
2022-01-23 12:05:48,379 INFO     core.py Клиент ('127.0.0.1', 63075) отключился от сервера.
2022-01-23 12:05:51,745 DEBUG    decos.py Была вызвана функция main c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>
2022-01-23 14:39:16,106 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:39:16,107 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 14:39:16,109 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 14:39:16,110 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:39:16,140 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 14:39:55,897 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:39:55,898 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 14:39:55,899 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 14:39:55,900 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:39:55,937 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 14:39:59,059 DEBUG    decos.py Была вызвана функция main c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>
2022-01-23 14:41:37,750 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:41:37,751 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 14:41:37,752 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 14:41:37,753 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:41:37,774 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 14:41:40,390 DEBUG    decos.py Была вызвана функция main c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>
2022-01-23 14:44:07,445 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:44:07,445 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 14:44:07,446 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 14:44:07,447 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:44:07,467 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 14:46:22,950 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:46:22,952 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 14:46:22,957 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 14:46:22,957 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:46:23,000 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 14:49:07,828 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:49:07,828 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 14:49:07,831 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 14:49:07,832 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:49:07,878 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 14:49:38,145 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:49:38,145 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 14:49:38,147 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 14:49:38,147 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:49:38,179 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 14:49:41,914 DEBUG    decos.py Была вызвана функция main c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>
2022-01-23 14:50:56,177 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:50:56,177 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 14:50:56,179 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 14:50:56,179 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:50:56,203 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 14:50:59,393 DEBUG    decos.py Была вызвана функция main c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>
2022-01-23 14:51:19,517 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:51:19,517 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 14:51:19,519 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 14:51:19,519 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 14:51:19,539 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 15:42:18,232 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 15:42:18,235 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 15:42:18,237 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 15:42:18,237 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 15:42:18,265 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 15:42:41,599 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 15:42:41,599 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 15:42:41,601 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 15:42:41,601 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 15:42:41,621 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 15:42:46,505 DEBUG    decos.py Была вызвана функция main c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции <module>
2022-01-23 15:43:13,611 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 15:43:13,611 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 15:43:13,613 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 15:43:13,613 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 15:43:13,630 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 15:43:29,737 INFO     core.py Установлено соедение с ПК ('127.0.0.1', 51793)
2022-01-23 15:43:30,238 DEBUG    core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1642941809.747104, 'user': {'account_name': 'w', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1q0KYP3zH5a6o+nP0cl5\nFsmBVoSoL1HxJBBDbaHUTa2rWhKqG0STgqgQoxpQ+i+WIonwWvpMv/4v6TeZHjih\nlasHaMEeDy2ZOHQ3d5iCQMUcGgreXiDwpgui7s/6A9SoXxgem1+hSujJwlomuNAb\nUnr/QqeOetAAhdtuXrlBADkQgq0iY7DhLmpa2MBArirX2fAxDpUgf9Djb+wO3/Wr\nSGopIOpZpS09NIHekHKOCJqu8Lbw0VgXOVrmTmQbFJEPaos6209XpU1L+ZyN84K/\nvuCXKCRH9vBDfkMxCAbhWHVsk7kMTQkejqdu8r1H/ZgF05oHO4iY7jJHUcBlcgx7\nTQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-01-23 15:43:30,239 DEBUG    core.py Start auth process for {'account_name': 'w', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1q0KYP3zH5a6o+nP0cl5\nFsmBVoSoL1HxJBBDbaHUTa2rWhKqG0STgqgQoxpQ+i+WIonwWvpMv/4v6TeZHjih\nlasHaMEeDy2ZOHQ3d5iCQMUcGgreXiDwpgui7s/6A9SoXxgem1+hSujJwlomuNAb\nUnr/QqeOetAAhdtuXrlBADkQgq0iY7DhLmpa2MBArirX2fAxDpUgf9Djb+wO3/Wr\nSGopIOpZpS09NIHekHKOCJqu8Lbw0VgXOVrmTmQbFJEPaos6209XpU1L+ZyN84K/\nvuCXKCRH9vBDfkMxCAbhWHVsk7kMTQkejqdu8r1H/ZgF05oHO4iY7jJHUcBlcgx7\nTQIDAQAB\n-----END PUBLIC KEY-----'}
2022-01-23 15:43:30,245 DEBUG    core.py Correct username, starting passwd check.
2022-01-23 15:43:30,247 DEBUG    core.py Auth message = {'response': 511, 'bin': '39e1297361df9a1f444c267603438a58da993f5d51932ed46d5e20a2beeabe7a3eaebb598463ab62e9e12932bda6020ce68482ead2264d82fa6e304d8a997557'}
2022-01-23 15:43:30,762 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1642941810.248697, 'account_name': 'w'}
2022-01-23 15:43:31,266 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1642941810.7777832, 'user': 'w'}
2022-01-23 15:43:39,283 DEBUG    core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1642941818.58423, 'account_name': 'kuznetsov'}
2022-01-23 15:43:42,789 DEBUG    core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1642941822.618443, 'account_name': 'w'}
2022-01-23 15:43:42,789 INFO     core.py Клиент ('127.0.0.1', 51793) отключился от сервера.
2022-01-23 16:40:32,468 DEBUG    decos.py Была вызвана функция config_load c параметрами (), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 16:40:32,469 DEBUG    server.py Инициализация парсера аргументов коммандной строки: ['/Users/kuznetsov/python/Клиент-серверные приложения на Python/data-base-and-PyQt/server.py']
2022-01-23 16:40:32,471 DEBUG    server.py Аргументы успешно загружены.
2022-01-23 16:40:32,472 DEBUG    decos.py Была вызвана функция arg_parser c параметрами ('7777', ''), {}. Вызов из модуля __main__.Вызов из функции main().Вызов из функции main
2022-01-23 16:40:32,495 INFO     core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-23 16:40:43,599 INFO     core.py Установлено соедение с ПК ('127.0.0.1', 52115)
2022-01-23 16:40:44,101 DEBUG    core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1642945243.609534, 'user': {'account_name': 'w', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1q0KYP3zH5a6o+nP0cl5\nFsmBVoSoL1HxJBBDbaHUTa2rWhKqG0STgqgQoxpQ+i+WIonwWvpMv/4v6TeZHjih\nlasHaMEeDy2ZOHQ3d5iCQMUcGgreXiDwpgui7s/6A9SoXxgem1+hSujJwlomuNAb\nUnr/QqeOetAAhdtuXrlBADkQgq0iY7DhLmpa2MBArirX2fAxDpUgf9Djb+wO3/Wr\nSGopIOpZpS09NIHekHKOCJqu8Lbw0VgXOVrmTmQbFJEPaos6209XpU1L+ZyN84K/\nvuCXKCRH9vBDfkMxCAbhWHVsk7kMTQkejqdu8r1H/ZgF05oHO4iY7jJHUcBlcgx7\nTQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-01-23 16:40:44,101 DEBUG    core.py Start auth process for {'account_name': 'w', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1q0KYP3zH5a6o+nP0cl5\nFsmBVoSoL1HxJBBDbaHUTa2rWhKqG0STgqgQoxpQ+i+WIonwWvpMv/4v6TeZHjih\nlasHaMEeDy2ZOHQ3d5iCQMUcGgreXiDwpgui7s/6A9SoXxgem1+hSujJwlomuNAb\nUnr/QqeOetAAhdtuXrlBADkQgq0iY7DhLmpa2MBArirX2fAxDpUgf9Djb+wO3/Wr\nSGopIOpZpS09NIHekHKOCJqu8Lbw0VgXOVrmTmQbFJEPaos6209XpU1L+ZyN84K/\nvuCXKCRH9vBDfkMxCAbhWHVsk7kMTQkejqdu8r1H/ZgF05oHO4iY7jJHUcBlcgx7\nTQIDAQAB\n-----END PUBLIC KEY-----'}
2022-01-23 16:40:44,107 DEBUG    core.py Correct username, starting passwd check.
2022-01-23 16:40:44,109 DEBUG    core.py Auth message = {'response': 511, 'bin': 'a7ba5f9d1f46e2aebeb954ffa2769233e8686139c298ee085321ac029f1f0ab522c3510f1185ebd27c866ecc4f96d8807e8f033d8a52f4f78eb2135b8e473d1d'}
2022-01-23 16:40:44,624 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1642945244.1108348, 'account_name': 'w'}
2022-01-23 16:40:45,141 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1642945244.654409, 'user': 'w'}
2022-01-23 16:40:47,150 DEBUG    core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1642945246.676715, 'account_name': 'kuznetsov'}
2022-01-23 16:40:59,172 INFO     core.py Установлено соедение с ПК ('127.0.0.1', 52116)
2022-01-23 16:40:59,674 DEBUG    core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1642945259.182899, 'user': {'account_name': 'kuznetsov', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApfjRhJI/Zhc24i0fljX0\nIgnAJS+q4HOhlCyY1p6+16SwlAA76zpQDLSrTTNMj2hlDBF92ePgAyYL2yLZL5q/\n+drVAX+MSLAkC+VORF9usHjasrv3aG0v3UCUSFVzdGGo59WD8a7XSH4f7oqwCGHP\n/vUOL8pEAONPChgMJQTf6rd60b56HlPColofK46RZeh8Xxi9EmrElXijPIEsNxVa\nUxEeL7lLm71GcZv+lgyTHA2xSZlR+VzXBeuzKeKl5g+qxFNx70bWNqi9LgD6ErjK\nJtEus3lUIZHP3STrd7w/ajkTX4ypfkpLdt5GY6tKTHPZcbz2wTSJ7NQqMFSTQz0t\nTQIDAQAB\n-----END PUBLIC KEY-----'}}
2022-01-23 16:40:59,675 DEBUG    core.py Start auth process for {'account_name': 'kuznetsov', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApfjRhJI/Zhc24i0fljX0\nIgnAJS+q4HOhlCyY1p6+16SwlAA76zpQDLSrTTNMj2hlDBF92ePgAyYL2yLZL5q/\n+drVAX+MSLAkC+VORF9usHjasrv3aG0v3UCUSFVzdGGo59WD8a7XSH4f7oqwCGHP\n/vUOL8pEAONPChgMJQTf6rd60b56HlPColofK46RZeh8Xxi9EmrElXijPIEsNxVa\nUxEeL7lLm71GcZv+lgyTHA2xSZlR+VzXBeuzKeKl5g+qxFNx70bWNqi9LgD6ErjK\nJtEus3lUIZHP3STrd7w/ajkTX4ypfkpLdt5GY6tKTHPZcbz2wTSJ7NQqMFSTQz0t\nTQIDAQAB\n-----END PUBLIC KEY-----'}
2022-01-23 16:40:59,676 DEBUG    core.py Correct username, starting passwd check.
2022-01-23 16:40:59,677 DEBUG    core.py Auth message = {'response': 511, 'bin': '7a0ddcced5dcf5dc6ca38b10f0f275a0f10ace056d8e2e6818d7e898c48a097c5317c9d0f4f78991df4704ec5fff8ceb091123bd4cad19863324f2425a347ff6'}
2022-01-23 16:41:00,184 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1642945259.678334, 'account_name': 'kuznetsov'}
2022-01-23 16:41:00,687 DEBUG    core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1642945260.197186, 'user': 'kuznetsov'}
2022-01-23 16:41:03,192 DEBUG    core.py Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1642945262.720213, 'account_name': 'w'}
2022-01-23 16:41:07,201 DEBUG    core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'kuznetsov', 'to': 'w', 'time': 1642945267.131107, 'mess_text': 'cfdVaUHiuG2OSUhzITSTq2GEsIrHZPwKCZ/mKgbiYDVwJ700XJ3eUOtLsUdtF35Fcv8gCjK2yOIbD7ckVv9yxQMSW13+Ezzn8vsoZA+80BEkTqL+DPiZPJRqOr6X2yCaxmpyC/IU/an/GjjjvBJiQmPXSKlVR75fhE/ZdOeYAM4Ir5B+HjTowWyO/x0hNw1p5JfO//TKbI8uKem7RKiaCopdU+ZIPOBZXBnHj8O41Zg+I9Beqiq7dgHlxXVyQ28iICsy/qUkTI0+WroslM59auWzHu0j1gHl/BfjMwaC/w+cskdJdwZkaEWfxuV9WcECxxmWGK+ROl2PDtYcPJwJzg=='}
2022-01-23 16:41:07,211 INFO     core.py Отправлено сообщение пользователю w от пользователя kuznetsov.
2022-01-23 16:41:18,229 DEBUG    core.py Разбор сообщения от клиента : {'action': 'message', 'from': 'w', 'to': 'kuznetsov', 'time': 1642945277.871974, 'mess_text': 'AEc35G/f13ZR99sqPRpWiMt2F70TOR0ZBBoYf6nOyXAcwiC2PAb/SX6pj30hdQqMkIW9U85hxHyn+cc/kzQ6VS8ValqEkgwlswIgP869X5OSSpI/SbDv2AxnkFD8IIDHeW3jN6FadmOtqqdvwCwLKiebwmRuy6zLt/wPR33eIqz++OIV8zM1YhQaL7IJz+b5XJVRMzsDzXWEf0ww6yI/6oDjEEUo0trr/9bqGfD3UZUKcuv7wZogvH9aZV4loRZCUKiZkkGbO9Hhv7URve/RMQu5jp7fe0qrXOBJNzoZu4oXG/fNsn0SMgckXl4cQdOMYn2OAqiLHcAtd8pRzWCmqw=='}
2022-01-23 16:41:18,242 INFO     core.py Отправлено сообщение пользователю kuznetsov от пользователя w.
